<h1><u>FBI project</u></h1>

In [5]:
import pandas as pd
import numpy as np

from sklearn import datasets
from sklearn.model_selection import cross_val_predict
from sklearn import linear_model
import matplotlib.pyplot as plt

<h3><i>Import data from excel file.</i></h3>

In [32]:
data_frame = pd.read_excel(io ='table_8_offenses_known_to_law_enforcement_new_york_by_city_2013.xls',
                          sheetname = '13tbl8ny', header = 0)

In [33]:
data_frame.head(7)

City  Population  Violent\ncrime  \
0             Adams Village        1861               0   
1  Addison Town and Village        2577               3   
2             Akron Village        2846               3   
3                    Albany       97956             791   
4            Albion Village        6388              23   
5            Alfred Village        4089               5   
6          Allegany Village        1781               3   

   Murder and\nnonnegligent\nmanslaughter  Rape\n(revised\ndefinition)1  \
0                                       0                           NaN   
1                                       0                           NaN   
2                                       0                           NaN   
3                                       8                           NaN   
4                                       0                           NaN   
5                                       0                           NaN   
6                                       0                           NaN   

   Rape\n(legacy\ndefinition)2  Robbery  Aggravated\nassault  Property\ncrime  \
0                            0        0                    0               12   
1                            0        0                    3               24   
2                            0        0                    3               16   
3                           30      227                  526             4090   
4                            3        4                   16              223   
5                            0        3                    2               46   
6                            0        0                    3               10   

   Burglary  Larceny-\ntheft  Motor\nvehicle\ntheft  Arson3  
0         2               10                      0     0.0  
1         3               20                      1     0.0  
2         1               15                      0     0.0  
3       705             3243                    142     NaN  
4        53              165                      5     NaN  
5        10               36                      0     NaN  
6         0               10                      0     0.0

In [34]:
data_frame.describe()

Population  Violent\ncrime  Murder and\nnonnegligent\nmanslaughter  \
count  3.480000e+02      348.000000                              348.000000   
mean   4.003763e+04      201.594828                                1.566092   
std    4.500374e+05     2815.268504                               18.303673   
min    5.260000e+02        0.000000                                0.000000   
25%    3.003000e+03        2.000000                                0.000000   
50%    7.233500e+03        6.000000                                0.000000   
75%    1.842750e+04       22.000000                                0.000000   
max    8.396126e+06    52384.000000                              335.000000   

       Rape\n(revised\ndefinition)1  Rape\n(legacy\ndefinition)2  \
count                           0.0                   348.000000   
mean                            NaN                     5.864943   
std                             NaN                    60.425452   
min                             NaN                     0.000000   
25%                             NaN                     0.000000   
50%                             NaN                     0.000000   
75%                             NaN                     2.000000   
max                             NaN                  1112.000000   

            Robbery  Aggravated\nassault  Property\ncrime      Burglary  \
count    348.000000           348.000000       348.000000    348.000000   
mean      72.902299           121.261494       792.606322    119.683908   
std     1031.032873          1706.131730      7659.724746    924.948789   
min        0.000000             0.000000         0.000000      0.000000   
25%        0.000000             1.000000        40.500000      6.000000   
50%        1.000000             4.000000       112.500000     17.500000   
75%        5.000000            14.000000       341.000000     51.250000   
max    19170.000000         31767.000000    141971.000000  16606.000000   

       Larceny-\ntheft  Motor\nvehicle\ntheft      Arson3  
count       348.000000             348.000000  187.000000  
mean        637.017241              35.905172    1.871658  
std        6346.054451             403.423826   10.693411  
min           0.000000               0.000000    0.000000  
25%          31.000000               0.000000    0.000000  
50%          94.000000               2.000000    0.000000  
75%         287.250000               7.000000    1.000000  
max      117931.000000            7434.000000  132.000000

<h3><i>Cleaning data.</i></h3>

In [35]:
# data_frame = data_frame.drop(data_frame.columns[[0,2,3,4,5,6,7,12 ]], axis=1)
data_frame = data_frame.drop(data_frame.columns[[0,2,4,8,12 ]], axis=1)

In [36]:
data_frame.head(3)

Population  Murder and\nnonnegligent\nmanslaughter  \
0        1861                                       0   
1        2577                                       0   
2        2846                                       0   

   Rape\n(legacy\ndefinition)2  Robbery  Aggravated\nassault  Burglary  \
0                            0        0                    0         2   
1                            0        0                    3         3   
2                            0        0                    3         1   

   Larceny-\ntheft  Motor\nvehicle\ntheft  
0               10                      0  
1               20                      1  
2               15                      0

In [37]:
cols = data_frame.columns.tolist()
cols

['Population',
 'Murder and\nnonnegligent\nmanslaughter',
 'Rape\n(legacy\ndefinition)2',
 'Robbery',
 'Aggravated\nassault',
 'Burglary',
 'Larceny-\ntheft',
 'Motor\nvehicle\ntheft']

<h3><i>1. Normalization.</i></h3>

In [38]:
data_frame = (data_frame - data_frame.mean())/data_frame.std()

<h3><i>2. We find the connection between burglary and other crimes.</i></h3>

In [14]:
X_burglary = data_frame.drop(data_frame.columns[[5]], axis=1)
X_burglary.head(3)

Population  Murder and\nnonnegligent\nmanslaughter  \
0   -0.084830                               -0.085562   
1   -0.083239                               -0.085562   
2   -0.082641                               -0.085562   

   Rape\n(legacy\ndefinition)2   Robbery  Aggravated\nassault  \
0                    -0.097061 -0.070708            -0.071074   
1                    -0.097061 -0.070708            -0.069316   
2                    -0.097061 -0.070708            -0.069316   

   Larceny-\ntheft  Motor\nvehicle\ntheft  
0        -0.098804              -0.089001  
1        -0.097228              -0.086522  
2        -0.098016              -0.089001

In [18]:
lr = linear_model.LinearRegression(normalize=True)
model_1 = lr.fit(X_burglary, data_frame['Burglary'])
# model.predict([1861,2, 10, 0])

In [19]:
model_1.coef_

array([-0.84480368,  0.22102495,  0.32374091, -0.98777085,  0.03616651,
        1.03091058,  1.20698661])

In [20]:
model_1.intercept_

7.6738102124804071e-18

The burglary crime dependents on population, robbery, larceny  theft, and motor vehicle theft. 

<h3><i>3. We find the connection between larceny theft and other crimes.</i></h3>

In [16]:
X_larceny_theft = data_frame.drop(data_frame.columns[[6]], axis=1)
X_larceny_theft.head(3)

Population  Murder and\nnonnegligent\nmanslaughter  \
0   -0.084830                               -0.085562   
1   -0.083239                               -0.085562   
2   -0.082641                               -0.085562   

   Rape\n(legacy\ndefinition)2   Robbery  Aggravated\nassault  Burglary  \
0                    -0.097061 -0.070708            -0.071074 -0.127233   
1                    -0.097061 -0.070708            -0.069316 -0.126152   
2                    -0.097061 -0.070708            -0.069316 -0.128314   

   Motor\nvehicle\ntheft  
0              -0.089001  
1              -0.086522  
2              -0.089001

In [24]:
model_2 = lr.fit(X_larceny_theft, data_frame['Larceny-\ntheft'])

In [25]:
model_2.coef_

array([  8.44364048e-01,  -1.18587084e-02,   3.61639449e-02,
        -6.71389753e-04,   8.33255167e-02,   3.80749935e-01,
        -3.25144181e-01])

In [26]:
model_2.intercept_

1.3552257390101638e-17

The larceny thieft dependents on population, robbery, burglary and motor vehicle theft.

<h3><i>4. We find the connection between motor vehicle theft and other crimes.</i></h3>

In [43]:
X_motor_theft = data_frame.drop(data_frame.columns[[7]], axis=1)
X_motor_theft.head(3)

Population  Murder and\nnonnegligent\nmanslaughter  \
0   -0.084830                               -0.085562   
1   -0.083239                               -0.085562   
2   -0.082641                               -0.085562   

   Rape\n(legacy\ndefinition)2   Robbery  Aggravated\nassault  Burglary  \
0                    -0.097061 -0.070708            -0.071074 -0.127233   
1                    -0.097061 -0.070708            -0.069316 -0.126152   
2                    -0.097061 -0.070708            -0.069316 -0.128314   

   Larceny-\ntheft  
0        -0.098804  
1        -0.097228  
2        -0.098016

In [44]:
model_3 = lr.fit(X_motor_theft, data_frame['Motor\nvehicle\ntheft'])

In [45]:
model_3.coef_

array([ 0.21515177, -0.04896464,  0.09146917,  1.24600988, -0.60197719,
        0.3803458 , -0.27741716])

In [46]:
model_3.intercept_

-2.6834692342633903e-17

The motor vehicle thieft dependents on population, robbery, aggravated assault, burlagry and larceny theft.